language: python
branches:
  only:
    - dev
    - staging
    - production
python:
  - "2.6"
before_install:
 - sudo apt-get update -qq
    - sudo apt-get install -qq python-swig
install:
  # Build/test dependencies
  - cd deploy ; pip install -r requirements.txt --use-mirrors
  - cd deploy ; pip install -r requirements-test.txt --use-mirrors
script: python manage.py test
notifications:
  irc:
    channels: "irc.freenode.org#vitasso"
    on_success: change
    on_failure: change
