language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
install:
  # Build/test dependencies
  - cd deploy ; pip install -r requirements.txt --use-mirrors
  - cd deploy ; pip install -r requirements-test.txt --use-mirrors
script: python manage.py test
notifications:
  irc:
    channels: "irc.freenode.org#vitasso"
    on_success: change
    on_failure: change
