language: python
branches:
  only:
    - dev
    - staging
    - production
python:
  - "2.6"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq swig
install:
  # Build/test dependencies
  - cd deploy
  - python create_commit_file.py
  - pip install -q -r requirements.txt --use-mirrors
  - pip install -q -r requirements-test.txt --use-mirrors
  - cd ..
script: python manage.py test api auth comments messages profiles --settings=test_settings
notifications:
  irc:
    channels: "irc.freenode.org#vitasso"
    on_success: change
    on_failure: change
